### ISSUE TITLE
"Reset window layout" doesn't work on Ubuntu (linux)

### ISSUE THREAD

**Issue by chiahaoliu** [NSLS-II-XPD/xpdView#22]
Don't know if that is platform specific problem, but it is worth looking as since beamline operation system are linux as well

**Comment by JKThanassi** [comment]
I guess that i should rename the option "redock all windows" because all it is doing is re-docking the dockwindows windows to the main window. Is that not working on linux?

**Comment by cduff4464** [comment]
I know sometimes that if the windows were sized in a different shape than what they were pulled out at, the reducing option makes them look a little strange, but I can still find them all there. They just usually become tabs of each other.

Is that what was happening for you @chiahaoliu

**Comment by chiahaoliu** [comment]
Yes, I tested a bit. I think I was confused by the word "reset". It is actually redock floating windows.

Anyway, it works, sorry for confusing and may be we can make it as "redock" to avoid this situation

**Comment by chiahaoliu** [comment]
@JKThanassi  @cduff4464  feel free to close it if you have read that comment

**Comment by cduff4464** [comment]
Thanks Tim I will rename it today
