### ISSUE TITLE
3D plot shuts user out of GUI

### ISSUE THREAD

**Issue by cduff4464** [NSLS-II-XPD/xpdView#24]
@JKThanassi  Hey when you used the code did the GUI lock you out? Every time I pop up a 3D window it locks me out of everything else

**Comment by JKThanassi** [comment]
@cduff4464 the windows should have been non-modal, ill make the change.

**Comment by cduff4464** [comment]
thanks also could you change you're naming to match mine, some of the files got mixed up when I did the merge

also thanks

**Comment by JKThanassi** [comment]
@cduff4464 do you mean in the license header?

**Comment by cduff4464** [comment]
no in your folder names, for some reason the waterfall_2d was in some other folder

**Comment by cduff4464** [comment]
I fixed it in mine, maybe it's not a problem in yours

**Comment by JKThanassi** [comment]
@cduff4464 oh, you made a folder that was not on my machine, thats why they were separated. Should be fixed now.

**Comment by cduff4464** [comment]
oh sorry I changed the name to match the name of the repository

**Comment by JKThanassi** [comment]
its all fixed 👌
