### ISSUE TITLE
RPP windows no longer updating after 2d_waterfall PR merge

### ISSUE THREAD

**Issue by JKThanassi** [NSLS-II-XPD/xpdView#25]
@cduff4464 were there conflicts around updating when merging the pr?

**Comment by cduff4464** [comment]
The very most recent one no. The merge before that, there were some merge issues, because of the different folders

**Comment by cduff4464** [comment]
My most recent commit should solve this problem. What was happening was that in the refresh method, the update r_rep method was only being called if only new tif files were found, not integrated data as well. This has been resolved by simply putting the call in for when new tif and integrated data is found
