### ISSUE TITLE
gui=qt in ipython_config.py is not always necessary 

### ISSUE THREAD

**Issue by chiahaoliu** [NSLS-II-XPD/xpdView#8]
@JKThanassi 
Just tested at beamline, whether we need to specify it or not seems to depend on conda environment (I am not sure where did it define) but if you defined it twice, your ipython seesion will halt

**Comment by CJ-Wright** [comment]
This is a good thing to check, I would personally prefer it if you didn't assume ipython. I try to use [xonsh](http://xon.sh/) as much as possible.

**Comment by cduff4464** [comment]
The solution to this will just be for now we will have users configure the ipython session by themselves
